// file consists types of events
module.exports = {
    COMMUNITY_CHAT:"COMMUNITY_CHAT",
    ADD_CHAT:"ADD_CHAT",
    USER_CONNECTED:"USER_CONNECTED",
    MESSAGE_RECIEVED:"MESSAGE_RECIEVED",
    MESSAGE_SENT:"MESSAGE_SENT",
    USER_DISCONNECTED:"USER_DISCONNECTED",
    TYPING:"TYPING",
    VERIFY_USER:"VERIFY_USER",
    PRIVATE_MESSAGE:"PRIVATE_MESSAGE",
    LOGOUT:"LOGOUT"
}