// file consists types of events
module.exports = {
    VERIFY_USER:"VERIFY_USER",
    USER_CONNECTED:"USER_CONNECTED",
    ADD_CHAT:"ADD_CHAT",
    MAIN_CHAT:"MAIN_CHAT",
    MESSAGE_SENT:"MESSAGE_SENT",
    MESSAGE_RECIEVED:"MESSAGE_RECIEVED",
    TYPING:"TYPING",
    USER_TO_CHAT: "USER_TO_CHAT",
    USER_IN_CHAT: "USER_IN_CHAT",
    USER_DISCONNECTED:"USER_DISCONNECTED",
    LOGOUT:"LOGOUT"
}